### ISSUE TITLE
Implement list community component

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome-Web#1]
* Implement list community component

**Comment by gangadhargo** [comment]
@jmprathab can I start work on this? how should be the community UI should look like. do you have UX

**Comment by jmprathab** [comment]
@gangadhargo I have implemented the UI with Bootstrap. I am working on porting the changes to this repo. We can have a quick chat or call if required. So, that you can work on it parallelly.

Let me know your thoughts. Thanks

**Comment by jmprathab** [comment]
![Screenshot 2020-07-12 at 12 33 20 PM](https://user-images.githubusercontent.com/11979066/87240971-ee660780-c43b-11ea-99cf-fa7585a47d55.png)

This is the screenshot of the UI which I have have implemented in Bootstrap(without React).

**Comment by jmprathab** [comment]
@gangadhargo Please join this [discord server](https://discord.gg/CngACKh) for discussion if required.

**Comment by jmprathab** [comment]
Implemented these in the latest checkin. Hence, closing the issue.

**Comment by gangadhargo** [comment]
@jmprathab sure. joined the discord server
