### ISSUE TITLE
Add key property to render in CommunityList

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome-Web#11]
Add a key property when iterating trough the list of communities in the CommunityList component.
[Relevant line can be found here.](https://github.com/jmprathab/MyHome-Web/blob/25b068366532706ce224bb9088d7bbcea803e4c5/src/components/community-list/community-list.component.jsx#L30)

Console error:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `CommunityList`. See https://fb.me/react-warning-keys for more information.
    in div (at community-list.component.jsx:30)
    in CommunityList (at homepage.component.jsx:9)
    in div (at homepage.component.jsx:7)
    in HomePage (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at App.js:43)
    in Switch (at App.js:42)
    in div (at App.js:40)
    in div (at App.js:39)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:11)
    in Provider (at src/index.js:10)
```

**Comment by navkumar258** [comment]
@Tobi406 Tried looking it up, try using the below change and confirm if its working:

**<Card key={community.communityId} id={community.communityId} name={community.name} district={community.district} />**

Sorry, didn't have the time to do it myself.
Hope it helps, thanks :smile:
