### ISSUE TITLE
GitHub PR Greeter fails

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome-Web#25]
## 🐛 Describe the bug
The GitHub PR Greeter fails, this is likely 

## ⚠️ Current behavior
Fails with the message `##[error]Resource not accessible by integration`. As I haven't found any solution in below mentioned issue, we should maybe strive to delete this Action.

[Issue on actions/first-interaction](https://github.com/actions/first-interaction/issues/10)

## ✅ Expected behavior
The PR is greeted successfully.

## 💣 Steps to reproduce
Create a PR

**Comment by jmprathab** [comment]
Deleted the action in recent commit. Hence, closing this.
