### ISSUE TITLE
Merge similar API classes

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome-Web#26]
## ⚠️ Is your feature request related to a problem? Please describe
The API classes we use to communicate with the back-end are splittered and makes it more complicated in my opinion.

## 💡 Describe the solution you'd like
Make the classes cover multiple use cases, eg. one general to getting, adding and removing houses, one for house members, etc., things that are needed for all of the methods in the class should be in the constructor (eg. house id, token)

**Comment by jmprathab** [comment]
@Tobi406 certain decisions were made to make it easier and convenient to implement user access control, permissions in the future.

Having said that, there is absolutely no point in making the API ugly and complicated for the end user, so +1 for your thoughts. For sure, we should be cleaning up the API endpoints, In case you have a concrete example in mind, please leave a note.

**Comment by Tobi406** [comment]
I think I made a mistake in the title, sorry for that.

What I meant was that we have lots of API classes that do a similar thing (if my PR is merged even more). An example is [AddCommunityAdministrators.js](https://github.com/jmprathab/MyHome-Web/blob/master/src/api/AddCommunityAdministrators.js) and [GetAdmins.js](https://github.com/jmprathab/MyHome-Web/blob/master/src/api/GetAdmins.js). Both related to one topic (admins) and with similar arguments (communityId, token)
