### ISSUE TITLE
Ability to delete house from Community

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome-Web#59]
## ⚠️ Is your feature request related to a problem? Please describe

* Ability to delete house from Community

## 💡 Describe the solution you'd like

* Users should be able to delete house from community list

**Comment by Tobi406** [comment]
This is probably a back-end error (jmprathab/MyHome#131) which is fixed by jmprathab/MyHome#133.

**Comment by Tobi406** [comment]
Closing as #133 was merged.
