### ISSUE TITLE
Add house to community not working

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome-Web#61]
## 🐛 Describe the bug

* Add house to community not working

## ⚠️ Current behavior

* Page does not do anything when trying to add house to community

**Comment by saraogipraveen** [comment]
This seems to be working fine in React Application. This issue can be closed


![addhousetocommmunity](https://user-images.githubusercontent.com/16433473/93009428-a8920080-f59e-11ea-94bd-856c7ae701bb.gif)

**Comment by jmprathab** [comment]
Thanks for the update @saraogipraveen and @Tobi406. Let us close this.
