### ISSUE TITLE
Add administrator to community not working

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome-Web#62]
## 🐛 Describe the bug

* Add administrator to community not working

## ⚠️ Current behavior

* Page does nothing when trying to add administrator to community

**Comment by saraogipraveen** [comment]
Hi @jmprathab, I was investigating this issue, I found out this. 
Are you referring to the below issue?
![myhome_issue](https://user-images.githubusercontent.com/16433473/93009284-9616c780-f59c-11ea-97bd-033df5a121fa.gif)

**Comment by jmprathab** [comment]
@saraogipraveen When I originally opened the issue, the page did absolutely nothing. Now as per your findings, the drop-down seems to be adding administrators which were even removed. Anyways, this seems to be a bug.

**Comment by saraogipraveen** [comment]
@jmprathab ok, I can take this up
