### ISSUE TITLE
Do not display welcome text once user is logged in

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome-Web#9]
Welcome text is being displayed asking user to login even though user has already logged in. Remove the welcome text once user logs in to the application.

![Screenshot 2020-07-14 at 9 42 44 AM](https://user-images.githubusercontent.com/11979066/87383225-66f0d380-c5b6-11ea-9a4e-f437326f3a49.png)

**Comment by sankita15** [comment]
@jmprathab can i pick this up?

**Comment by jmprathab** [comment]
@sankita15 Sure. Let me assign it to you so that people know you are working on this. Thanks!
