### ISSUE TITLE
Increase left value of sidebar

### ISSUE THREAD

**Issue by Tobi406** [jmprathab/MyHome-Web#90]
## 🐛 Describe the bug
The sidebar does show even if it isn't opened

## ⚠️ Current behavior
The sidebar does show even if it isn't opened

## ✅ Expected behavior
The sidebar doesn't show if it isn't opened but still shows if it is opened

## 💣 Steps to reproduce
Go with the screen width lower than 200px

## Tips for everyone who wants to work on this
- **Please submit a PR to the [rebranding](https://github.com/jmprathab/MyHome-Web/tree/rebranding) branch**
- Set the left property of the sidebar to something higher (see [Sidebar.jsx#L43](https://github.com/jmprathab/MyHome-Web/blob/b1d9fef22f8231349ad77734a6cd6999c8f07c0f/src/components/sidebar/Sidebar.jsx#L43))

**Comment by amohapatra123** [comment]
i want to work on this issue, please assign this to me

**Comment by ayush015** [comment]
I would like to work on this issue if it is still up for grabs!

**Comment by mubashiralisiddiqui** [comment]
Pull request created for this issue 
I have disable the sidebar on screen size less than 200px

**Comment by Tobi406** [comment]
Just some clarification: What I meant is the white part of the sidebar that shows **even tough it isn't activated**
![image](https://user-images.githubusercontent.com/43016900/95683924-5ddfc480-0bee-11eb-9cd2-98eae93f7fe9.png)
